"""tenants billing and devices

Revision ID: c542ed62b26b
Revises: 8e2af841b0e3
Create Date: 2026-09-19 07:51:49.193586

"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c542ed62b26b'
down_revision: Union[str, Sequence[str], None] = '8e2af841b0e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', postgresql.ENUM('household', 'clinic', 'ovabmu', 'polyclinic', 'network', name='tenant_kind'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('legal_name', sa.Text(), nullable=True),
    sa.Column('tax_id', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=False),
    sa.Column('district', sa.Text(), nullable=True),
    sa.Column('owner_phone', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('serial_number', sa.Text(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('tier', postgresql.ENUM('tier1_wearos', 'tier2_wearos_budget', 'tier3_ble_band', name='device_tier'), nullable=False),
    sa.Column('status', postgresql.ENUM('in_stock', 'assigned', 'active', 'returning', 'maintenance', 'lost', 'retired', name='device_status'), nullable=False),
    sa.Column('ownership', sa.Text(), nullable=False),
    sa.Column('battery_health_pct', sa.SmallInteger(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('active_patients', sa.Integer(), nullable=False),
    sa.Column('amount_uzs', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plan', postgresql.ENUM('free', 'premium', 'premium_doc', 'clinic', name='plan_code'), nullable=False),
    sa.Column('status', postgresql.ENUM('trialing', 'active', 'past_due', 'canceled', 'free', name='sub_status'), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grace_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seats_included', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('card_token', sa.Text(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('provider_txn', sa.Text(), nullable=False),
    sa.Column('amount_uzs', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_txn', name='uq_payment_provider_txn')
    )
    op.create_table('device_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deposit_uzs', sa.BigInteger(), nullable=False),
    sa.Column('rental_uzs_month', sa.BigInteger(), nullable=False),
    sa.Column('due_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('returned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('return_notes', sa.Text(), nullable=True),
    sa.Column('deposit_refunded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('patients', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'patients', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_tenant_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'tenant_id')
    op.drop_constraint('patients_tenant_id_fkey', 'patients', type_='foreignkey')
    op.drop_column('patients', 'tenant_id')
    op.drop_table('device_assignments')
    op.drop_table('payments')
    op.drop_table('subscriptions')
    op.drop_table('invoices')
    op.drop_table('devices')
    op.drop_table('tenants')

    # Enum types outlive their tables — drop them so upgrade is repeatable.
    op.execute('DROP TYPE IF EXISTS device_status')
    op.execute('DROP TYPE IF EXISTS device_tier')
    op.execute('DROP TYPE IF EXISTS plan_code')
    op.execute('DROP TYPE IF EXISTS sub_status')
    op.execute('DROP TYPE IF EXISTS tenant_kind')

    # ### end Alembic commands ###
