"""architecture base schema

Revision ID: c1057cb46015
Revises: 
Create Date: 2026-09-22 03:59:22.786252

"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c1057cb46015'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _execute_many(sql: str) -> None:
    for statement in (part.strip() for part in sql.split(";")):
        if statement:
            op.execute(statement)


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('preferred_lang', postgresql.ENUM('uz', 'ru', 'en', name='lang_code'), server_default='uz', nullable=False),
    sa.Column('timezone', sa.Text(), server_default='Asia/Tashkent', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('surveys',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('audience', sa.Text(), nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kind', postgresql.ENUM('ovabmu', 'polyclinic', 'hospital', 'network', name='tenant_kind'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('legal_name', sa.Text(), nullable=True),
    sa.Column('tax_id', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=False),
    sa.Column('district', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_identities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_identity')
    )
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('patient_days_total', sa.Integer(), nullable=False),
    sa.Column('patient_days_with_data', sa.Integer(), nullable=False),
    sa.Column('min_commitment', sa.Integer(), nullable=False),
    sa.Column('billed_days', sa.Integer(), nullable=False),
    sa.Column('amount_uzs', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), server_default='open', nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('sex', sa.CHAR(length=1), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('jshshir', sa.Text(), nullable=True),
    sa.Column('preferred_lang', sa.Text(), server_default='uz', nullable=False),
    sa.Column('diagnosis', sa.Text(), server_default='', nullable=False),
    sa.Column('district', sa.Text(), server_default='', nullable=False),
    sa.Column('phase', sa.Text(), server_default='calib', nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('primary_icd10', sa.Text(), nullable=True),
    sa.Column('blood_group', sa.Text(), nullable=True),
    sa.Column('rh', sa.Text(), nullable=True),
    sa.Column('profile_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discharge_date', sa.Date(), nullable=True),
    sa.Column('baseline_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('baseline_approved_by', sa.UUID(), nullable=True),
    sa.Column('device_id', sa.Text(), nullable=True),
    sa.Column('pin_hash', sa.Text(), nullable=True),
    sa.Column('deceased_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deceased_marked_by', sa.UUID(), nullable=True),
    sa.Column('deceased_confirmed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sex IS NULL OR sex IN ('m','f')", name='chk_patient_sex'),
    sa.ForeignKeyConstraint(['baseline_approved_by'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['deceased_confirmed_by'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['deceased_marked_by'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_patients_alive', 'patients', ['id'], unique=False, postgresql_where=sa.text('deceased_at IS NULL'))
    op.create_index('idx_patients_phone', 'patients', ['phone'], unique=False, postgresql_where=sa.text('phone IS NOT NULL'))
    op.create_table('tenant_licences',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('device_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('min_days_per_device', sa.Integer(), server_default='10', nullable=False),
    sa.Column('price_per_patient_day_uzs', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('intake_blocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('tenant_members',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('role', postgresql.ENUM('nurse', 'doctor', 'head_doctor', 'admin', 'dispatcher', name='tenant_role'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'account_id', name='uq_member')
    )
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', postgresql.ENUM('green', 'amber', 'red', 'no_data', name='alert_level'), nullable=False),
    sa.Column('composite_score', sa.Float(), server_default='0', nullable=False),
    sa.Column('triggered_params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('data_quality', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'ts', name='uq_alert')
    )
    op.create_table('baselines',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('param', sa.Text(), nullable=False),
    sa.Column('time_window', sa.SmallInteger(), nullable=False),
    sa.Column('median', sa.Float(), nullable=False),
    sa.Column('mad', sa.Float(), nullable=False),
    sa.Column('n_samples', sa.Integer(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('includes_attributed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('patient_id', 'param', 'time_window')
    )
    op.create_table('billing_days',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('had_data', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'patient_id', 'day')
    )
    op.create_table('devices',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('serial', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('tier', sa.Text(), server_default='tier1_wearos', nullable=False),
    sa.Column('ownership', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('in_stock', 'assigned', 'maintenance', 'lost', 'retired', name='device_status'), server_default='in_stock', nullable=False),
    sa.Column('owner_tenant_id', sa.UUID(), nullable=True),
    sa.Column('owner_patient_id', sa.UUID(), nullable=True),
    sa.Column('battery_health_pct', sa.SmallInteger(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bound_phone_node_id', sa.Text(), nullable=True),
    sa.Column('bound_phone_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('num_nonnulls(owner_tenant_id, owner_patient_id) <= 1', name='chk_single_owner'),
    sa.ForeignKeyConstraint(['owner_patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial')
    )
    op.create_table('member_territories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_member_id', sa.UUID(), nullable=False),
    sa.Column('mahalla', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_member_id'], ['tenant_members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_member_id', 'mahalla', name='uq_member_mahalla')
    )
    op.create_table('patient_access',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('role', postgresql.ENUM('payer', 'caregiver', name='access_role'), server_default='caregiver', nullable=False),
    sa.Column('relation', sa.Text(), nullable=True),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'account_id', name='uq_access')
    )
    op.create_index('idx_access_active', 'patient_access', ['account_id'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('relative_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('num_nonnulls(account_id, relative_id, patient_id) = 1', name='chk_refresh_token_owner'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relative_id'], ['patient_access.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('patient_addresses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('region', sa.Text(), nullable=False),
    sa.Column('district', sa.Text(), nullable=False),
    sa.Column('mahalla', sa.Text(), nullable=True),
    sa.Column('street', sa.Text(), nullable=True),
    sa.Column('house', sa.Text(), nullable=True),
    sa.Column('flat', sa.Text(), nullable=True),
    sa.Column('landmark', sa.Text(), nullable=True),
    sa.Column('entrance_note', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_one_primary_address', 'patient_addresses', ['patient_id'], unique=True, postgresql_where=sa.text('is_primary'))
    op.create_table('patient_allergies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('substance', sa.Text(), nullable=False),
    sa.Column('reaction', sa.Text(), nullable=True),
    sa.Column('severity', sa.Text(), server_default='moderate', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_conditions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('icd10', sa.Text(), nullable=True),
    sa.Column('name_uz', sa.Text(), nullable=False),
    sa.Column('name_ru', sa.Text(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('severity_note', sa.Text(), nullable=True),
    sa.Column('diagnosed_at', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_consents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('scope', postgresql.ENUM('family_access', 'clinical_monitoring', name='consent_scope'), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('method', postgresql.ENUM('sms', 'in_app', 'verbal_by_clinician', name='consent_method'), nullable=False),
    sa.Column('witnessed_by', sa.UUID(), nullable=True),
    sa.Column('target_account_id', sa.UUID(), nullable=True),
    sa.Column('target_tenant_id', sa.UUID(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['target_tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['witnessed_by'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_consents_patient', 'patient_consents', ['patient_id', 'scope'], unique=False)
    op.create_table('patient_measurements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('sbp_mmhg', sa.SmallInteger(), nullable=True),
    sa.Column('dbp_mmhg', sa.SmallInteger(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_medications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('dose', sa.Text(), nullable=True),
    sa.Column('frequency', sa.Text(), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('stopped_at', sa.Date(), nullable=True),
    sa.Column('affects_params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('prescribed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescribed_by'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_memberships',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('kind', postgresql.ENUM('care', name='membership_kind'), server_default='care', nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.Column('baseline_decision', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_one_care_owner', 'patient_memberships', ['patient_id'], unique=True, postgresql_where=sa.text("kind = 'care' AND revoked_at IS NULL"))
    op.create_table('patient_risk_factors',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('smoking', sa.Text(), nullable=True),
    sa.Column('smoking_pack_years', sa.Float(), nullable=True),
    sa.Column('alcohol', sa.Text(), nullable=True),
    sa.Column('diabetes', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('hypertension', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ckd', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('physical_activity', sa.Text(), nullable=True),
    sa.Column('lives_alone', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('mobility', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_table('patient_subscriptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('plan', postgresql.ENUM('free', 'premium', 'premium_doc', name='sub_plan'), server_default='free', nullable=False),
    sa.Column('status', postgresql.ENUM('trialing', 'active', 'past_due', 'lapsed', name='sub_status'), server_default='trialing', nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_paid_by', sa.UUID(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('provider_ref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['last_paid_by'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('profile_audit',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('actor_kind', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('entity', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sos_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('realtime_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_realtime_events_created_at', 'realtime_events', ['created_at'], unique=False)
    op.create_index('idx_realtime_events_topic_id', 'realtime_events', ['topic', 'id'], unique=False)
    op.create_table('survey_responses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('twin_snapshots',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_assignments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('provenance', postgresql.ENUM('clinic_issued', 'self_purchased', 'unknown', name='device_provenance'), server_default='unknown', nullable=False),
    sa.Column('supervised', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('deposit_uzs', sa.BigInteger(), nullable=True),
    sa.Column('rental_uzs_month', sa.BigInteger(), nullable=True),
    sa.Column('due_back_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('return_notes', sa.Text(), nullable=True),
    sa.Column('deposit_refunded', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assignment_window', 'device_assignments', ['device_id', 'assigned_at', 'released_at'], unique=False)
    op.create_table('device_credentials',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('secret_hash', sa.Text(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_table('device_enrollment_codes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medication_responses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('medication_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('baseline_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('baseline_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('response_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('response_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('observed_effects', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('verdict', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['patient_medications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('recipient_account_id', sa.UUID(), nullable=True),
    sa.Column('alert_id', sa.BigInteger(), nullable=True),
    sa.Column('level', postgresql.ENUM('green', 'amber', 'red', 'no_data', name='alert_level'), nullable=True),
    sa.Column('urgent', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orphan_readings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_to_patient_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['resolved_to_patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'window_start', name='uq_orphan_key')
    )
    op.create_index('idx_orphan_unresolved', 'orphan_readings', ['device_id', 'window_start'], unique=False, postgresql_where=sa.text('resolved_at IS NULL'))
    op.create_table('patient_outcomes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('icd10', sa.Text(), nullable=True),
    sa.Column('predicted_by_alert_id', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['predicted_by_alert_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recorded_by'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('patient_subscription_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('provider_ref', sa.Text(), nullable=False),
    sa.Column('amount_uzs', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_subscription_id'], ['patient_subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_ref', name='uq_payment_provider_ref')
    )
    op.create_table('sos_notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sos_event_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('recipient', sa.Text(), nullable=False),
    sa.Column('delivered', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sos_event_id'], ['sos_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('assignee_account_id', sa.UUID(), nullable=False),
    sa.Column('kind', postgresql.ENUM('clinical', 'technical', name='task_kind'), nullable=False),
    sa.Column('status', postgresql.ENUM('open', 'acknowledged', 'done', 'overdue', 'cancelled', name='task_status'), server_default='open', nullable=False),
    sa.Column('alert_id', sa.BigInteger(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('assignee_account_id IS NOT NULL', name='chk_assignee'),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assignee_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_attempts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('notification_id', sa.BigInteger(), nullable=False),
    sa.Column('channel', postgresql.ENUM('push', 'telegram', 'sms', 'voice', name='notify_channel'), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivered', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('readings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('device_assignment_id', sa.UUID(), nullable=True),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hr_mean', sa.Float(), nullable=True),
    sa.Column('hr_min', sa.Float(), nullable=True),
    sa.Column('hr_max', sa.Float(), nullable=True),
    sa.Column('rmssd', sa.Float(), nullable=True),
    sa.Column('sdnn', sa.Float(), nullable=True),
    sa.Column('spo2', sa.Float(), nullable=True),
    sa.Column('skin_temp', sa.Float(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('rr_est', sa.Float(), nullable=True),
    sa.Column('sleep_frag', sa.Float(), nullable=True),
    sa.Column('worn', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('worn_pct', sa.SmallInteger(), nullable=True),
    sa.Column('samples_n', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('battery', sa.SmallInteger(), nullable=True),
    sa.Column('device_clock_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clock_offset_ms', sa.Integer(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('provenance', postgresql.ENUM('clinic_issued', 'self_purchased', 'unknown', name='device_provenance'), server_default='unknown', nullable=False),
    sa.Column('attributed_by', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_assignment_id'], ['device_assignments.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'window_start'),
    sa.UniqueConstraint('device_id', 'window_start', name='uq_reading_key'),
    postgresql_partition_by='RANGE (window_start)'
    )
    op.execute(
        """
        CREATE TABLE readings_default PARTITION OF readings DEFAULT;
        """
    )
    op.execute(
        """
        DO $$
        DECLARE
            month_start date := date_trunc('month', now())::date;
            part_start date;
            part_end date;
            part_name text;
            i int;
        BEGIN
            FOR i IN 0..3 LOOP
                part_start := (month_start + (i || ' month')::interval)::date;
                part_end := (month_start + ((i + 1) || ' month')::interval)::date;
                part_name := 'readings_' || to_char(part_start, 'YYYY_MM');
                EXECUTE format(
                    'CREATE TABLE IF NOT EXISTS %I PARTITION OF readings FOR VALUES FROM (%L) TO (%L)',
                    part_name,
                    part_start,
                    part_end
                );
            END LOOP;
        END $$;
        """
    )
    _execute_many(
        """
        ALTER TABLE patients ENABLE ROW LEVEL SECURITY;
        ALTER TABLE patients FORCE ROW LEVEL SECURITY;

        CREATE POLICY patients_scope ON patients
        FOR ALL
        USING (
            current_setting('wmax.bypass', true) = 'on'
            OR EXISTS (
                SELECT 1
                FROM patient_memberships m
                WHERE m.patient_id = patients.id
                  AND m.revoked_at IS NULL
                  AND m.tenant_id::text = ANY(
                      string_to_array(current_setting('wmax.tenant_ids', true), ',')
                  )
            )
            OR EXISTS (
                SELECT 1
                FROM patient_access a
                WHERE a.patient_id = patients.id
                  AND a.revoked_at IS NULL
                  AND a.account_id::text = current_setting('wmax.account_id', true)
            )
            OR patients.id::text = ANY(
                string_to_array(current_setting('wmax.patient_ids', true), ',')
            )
        )
        WITH CHECK (
            current_setting('wmax.bypass', true) = 'on'
            OR NULLIF(current_setting('wmax.account_id', true), '') IS NOT NULL
        );

        ALTER TABLE readings ENABLE ROW LEVEL SECURITY;
        ALTER TABLE readings FORCE ROW LEVEL SECURITY;

        CREATE POLICY readings_scope ON readings
        FOR ALL
        USING (
            current_setting('wmax.bypass', true) = 'on'
            OR EXISTS (SELECT 1 FROM patients p WHERE p.id = readings.patient_id)
            OR EXISTS (
                SELECT 1
                FROM device_assignments da
                WHERE da.id = readings.device_assignment_id
                  AND da.device_id = readings.device_id
                  AND da.patient_id = readings.patient_id
                  AND da.device_id::text = current_setting('wmax.device_id', true)
                  AND da.assigned_at <= readings.window_start
                  AND (da.released_at IS NULL OR da.released_at > readings.window_start)
            )
        )
        WITH CHECK (
            current_setting('wmax.bypass', true) = 'on'
            OR EXISTS (SELECT 1 FROM patients p WHERE p.id = readings.patient_id)
            OR EXISTS (
                SELECT 1
                FROM device_assignments da
                WHERE da.id = readings.device_assignment_id
                  AND da.device_id = readings.device_id
                  AND da.patient_id = readings.patient_id
                  AND da.device_id::text = current_setting('wmax.device_id', true)
                  AND da.assigned_at <= readings.window_start
                  AND (da.released_at IS NULL OR da.released_at > readings.window_start)
            )
        );

        ALTER TABLE alerts ENABLE ROW LEVEL SECURITY;
        ALTER TABLE alerts FORCE ROW LEVEL SECURITY;
        CREATE POLICY alerts_scope ON alerts
        FOR ALL
        USING (
            current_setting('wmax.bypass', true) = 'on'
            OR EXISTS (SELECT 1 FROM patients p WHERE p.id = alerts.patient_id)
        )
        WITH CHECK (
            current_setting('wmax.bypass', true) = 'on'
            OR EXISTS (SELECT 1 FROM patients p WHERE p.id = alerts.patient_id)
        );

        ALTER TABLE device_assignments ENABLE ROW LEVEL SECURITY;
        ALTER TABLE device_assignments FORCE ROW LEVEL SECURITY;
        CREATE POLICY device_assignments_scope ON device_assignments
        FOR ALL
        USING (
            current_setting('wmax.bypass', true) = 'on'
            OR EXISTS (SELECT 1 FROM patients p WHERE p.id = device_assignments.patient_id)
            OR device_id::text = current_setting('wmax.device_id', true)
        )
        WITH CHECK (
            current_setting('wmax.bypass', true) = 'on'
            OR EXISTS (SELECT 1 FROM patients p WHERE p.id = device_assignments.patient_id)
        );

        ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
        ALTER TABLE tasks FORCE ROW LEVEL SECURITY;
        CREATE POLICY tasks_scope ON tasks
        FOR ALL
        USING (
            current_setting('wmax.bypass', true) = 'on'
            OR tenant_id::text = ANY(
                string_to_array(current_setting('wmax.tenant_ids', true), ',')
            )
            OR assignee_account_id::text = current_setting('wmax.account_id', true)
        )
        WITH CHECK (
            current_setting('wmax.bypass', true) = 'on'
            OR tenant_id::text = ANY(
                string_to_array(current_setting('wmax.tenant_ids', true), ',')
            )
        );

        ALTER TABLE patient_consents ENABLE ROW LEVEL SECURITY;
        ALTER TABLE patient_consents FORCE ROW LEVEL SECURITY;
        CREATE POLICY patient_consents_scope ON patient_consents
        FOR ALL
        USING (
            current_setting('wmax.bypass', true) = 'on'
            OR EXISTS (SELECT 1 FROM patients p WHERE p.id = patient_consents.patient_id)
        )
        WITH CHECK (
            current_setting('wmax.bypass', true) = 'on'
            OR EXISTS (SELECT 1 FROM patients p WHERE p.id = patient_consents.patient_id)
        );

        ALTER TABLE patient_conditions ENABLE ROW LEVEL SECURITY;
        ALTER TABLE patient_conditions FORCE ROW LEVEL SECURITY;
        CREATE POLICY patient_conditions_scope ON patient_conditions
        FOR ALL
        USING (
            current_setting('wmax.bypass', true) = 'on'
            OR EXISTS (SELECT 1 FROM patients p WHERE p.id = patient_conditions.patient_id)
        )
        WITH CHECK (
            current_setting('wmax.bypass', true) = 'on'
            OR EXISTS (SELECT 1 FROM patients p WHERE p.id = patient_conditions.patient_id)
        );

        ALTER TABLE patient_medications ENABLE ROW LEVEL SECURITY;
        ALTER TABLE patient_medications FORCE ROW LEVEL SECURITY;
        CREATE POLICY patient_medications_scope ON patient_medications
        FOR ALL
        USING (
            current_setting('wmax.bypass', true) = 'on'
            OR EXISTS (SELECT 1 FROM patients p WHERE p.id = patient_medications.patient_id)
        )
        WITH CHECK (
            current_setting('wmax.bypass', true) = 'on'
            OR EXISTS (SELECT 1 FROM patients p WHERE p.id = patient_medications.patient_id)
        );

        ALTER TABLE billing_days ENABLE ROW LEVEL SECURITY;
        ALTER TABLE billing_days FORCE ROW LEVEL SECURITY;
        CREATE POLICY billing_days_scope ON billing_days
        FOR ALL
        USING (
            current_setting('wmax.bypass', true) = 'on'
            OR tenant_id::text = ANY(
                string_to_array(current_setting('wmax.tenant_ids', true), ',')
            )
        )
        WITH CHECK (
            current_setting('wmax.bypass', true) = 'on'
            OR tenant_id::text = ANY(
                string_to_array(current_setting('wmax.tenant_ids', true), ',')
            )
        );

        ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;
        ALTER TABLE invoices FORCE ROW LEVEL SECURITY;
        CREATE POLICY invoices_scope ON invoices
        FOR ALL
        USING (
            current_setting('wmax.bypass', true) = 'on'
            OR tenant_id::text = ANY(
                string_to_array(current_setting('wmax.tenant_ids', true), ',')
            )
        )
        WITH CHECK (
            current_setting('wmax.bypass', true) = 'on'
            OR tenant_id::text = ANY(
                string_to_array(current_setting('wmax.tenant_ids', true), ',')
            )
        );
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # RLS policies reference other tables (e.g. patients_scope reads
    # patient_memberships), so they must go before any table is dropped.
    op.execute("DROP POLICY IF EXISTS patients_scope ON patients")
    op.execute("DROP POLICY IF EXISTS readings_scope ON readings")
    op.execute("DROP POLICY IF EXISTS alerts_scope ON alerts")
    op.execute("DROP POLICY IF EXISTS device_assignments_scope ON device_assignments")
    op.execute("DROP POLICY IF EXISTS tasks_scope ON tasks")
    op.execute("DROP POLICY IF EXISTS patient_consents_scope ON patient_consents")
    op.execute("DROP POLICY IF EXISTS patient_conditions_scope ON patient_conditions")
    op.execute("DROP POLICY IF EXISTS patient_medications_scope ON patient_medications")
    op.execute("DROP POLICY IF EXISTS billing_days_scope ON billing_days")
    op.execute("DROP POLICY IF EXISTS invoices_scope ON invoices")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('readings')
    # refresh_tokens references patient_access, so it goes first.
    op.drop_table('refresh_tokens')
    op.drop_index('idx_realtime_events_topic_id', table_name='realtime_events')
    op.drop_index('idx_realtime_events_created_at', table_name='realtime_events')
    op.drop_table('realtime_events')
    op.drop_table('notification_attempts')
    op.drop_table('tasks')
    op.drop_table('sos_notifications')
    op.drop_table('payments')
    op.drop_table('patient_outcomes')
    op.drop_index('idx_orphan_unresolved', table_name='orphan_readings', postgresql_where=sa.text('resolved_at IS NULL'))
    op.drop_table('orphan_readings')
    op.drop_table('notifications')
    op.drop_table('medication_responses')
    op.drop_table('device_enrollment_codes')
    op.drop_table('device_credentials')
    op.drop_index('idx_assignment_window', table_name='device_assignments')
    op.drop_table('device_assignments')
    op.drop_table('twin_snapshots')
    op.drop_table('survey_responses')
    op.drop_table('sos_events')
    op.drop_table('profile_audit')
    op.drop_table('patient_subscriptions')
    op.drop_table('patient_risk_factors')
    op.drop_index('idx_one_care_owner', table_name='patient_memberships', postgresql_where=sa.text("kind = 'care' AND revoked_at IS NULL"))
    op.drop_table('patient_memberships')
    op.drop_table('patient_medications')
    op.drop_table('patient_measurements')
    op.drop_index('idx_consents_patient', table_name='patient_consents')
    op.drop_table('patient_consents')
    op.drop_table('patient_conditions')
    op.drop_table('patient_allergies')
    op.drop_index('idx_one_primary_address', table_name='patient_addresses', postgresql_where=sa.text('is_primary'))
    op.drop_table('patient_addresses')
    op.drop_index('idx_access_active', table_name='patient_access', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('patient_access')
    op.drop_table('member_territories')
    op.drop_table('devices')
    op.drop_table('billing_days')
    op.drop_table('baselines')
    op.drop_table('alerts')
    op.drop_table('tenant_members')
    op.drop_table('tenant_licences')
    op.drop_index('idx_patients_phone', table_name='patients', postgresql_where=sa.text('phone IS NOT NULL'))
    op.drop_index('idx_patients_alive', table_name='patients', postgresql_where=sa.text('deceased_at IS NULL'))
    op.drop_table('patients')
    op.drop_table('invoices')
    op.drop_table('account_identities')
    op.drop_table('tenants')
    op.drop_table('surveys')
    op.drop_table('accounts')
    for enum_name in (
        'access_role',
        'alert_level',
        'consent_method',
        'consent_scope',
        'device_provenance',
        'device_status',
        'lang_code',
        'membership_kind',
        'notify_channel',
        'sub_plan',
        'sub_status',
        'task_kind',
        'task_status',
        'tenant_kind',
        'tenant_role',
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
    # ### end Alembic commands ###
