"""initial schema from ORM models

Revision ID: 8e2af841b0e3
Revises: 
Create Date: 2026-09-19 01:29:35.149011

"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8e2af841b0e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', postgresql.ENUM('doctor', 'nurse', 'admin', name='user_role'), nullable=False),
    sa.Column('district', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('age', sa.SmallInteger(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('sex', sa.CHAR(length=1), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('district', sa.Text(), nullable=False),
    sa.Column('discharge_date', sa.Date(), nullable=True),
    sa.Column('phase', postgresql.ENUM('calib', 'learning', 'full', name='patient_phase'), nullable=False),
    sa.Column('phase_since', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('baseline_approved_by', sa.UUID(), nullable=True),
    sa.Column('baseline_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('nurse_id', sa.UUID(), nullable=True),
    sa.Column('device_id', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('pin_hash', sa.Text(), nullable=True),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('primary_icd10', sa.Text(), nullable=True),
    sa.Column('primary_address_id', sa.UUID(), nullable=True),
    sa.Column('blood_group', postgresql.ENUM('O', 'A', 'B', 'AB', name='blood_group'), nullable=True),
    sa.Column('rh', postgresql.ENUM('pos', 'neg', name='rh_factor'), nullable=True),
    sa.Column('preferred_lang', sa.Text(), server_default='uz', nullable=False),
    sa.Column('profile_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['baseline_approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['nurse_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['primary_address_id'], ['patient_addresses.id'], name='fk_patients_primary_address', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', postgresql.ENUM('green', 'amber', 'red', 'no_data', name='alert_level'), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('triggered_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'ts', name='uq_alert')
    )
    op.create_table('baselines',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('param', postgresql.ENUM('hr_mean', 'rmssd', 'spo2', 'skin_temp', 'sleep_frag', 'steps', 'rr_est', name='baseline_param'), nullable=False),
    sa.Column('time_window', sa.SmallInteger(), nullable=False),
    sa.Column('median', sa.Float(), nullable=False),
    sa.Column('mad', sa.Float(), nullable=False),
    sa.Column('n_samples', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'param', 'time_window', name='uq_baseline')
    )
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('recipient', sa.Text(), nullable=False),
    sa.Column('level', postgresql.ENUM('green', 'amber', 'red', 'no_data', name='alert_level'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('kind', postgresql.ENUM('home', 'temporary', 'work', 'other', name='address_kind'), nullable=False),
    sa.Column('region', sa.Text(), nullable=False),
    sa.Column('district', sa.Text(), nullable=False),
    sa.Column('mahalla', sa.Text(), nullable=True),
    sa.Column('street', sa.Text(), nullable=True),
    sa.Column('house', sa.Text(), nullable=True),
    sa.Column('flat', sa.Text(), nullable=True),
    sa.Column('landmark', sa.Text(), nullable=True),
    sa.Column('entrance_note', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('geo_source', sa.Text(), nullable=True),
    sa.Column('geo_accuracy_m', sa.Float(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_allergies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('substance', sa.Text(), nullable=False),
    sa.Column('reaction', sa.Text(), nullable=True),
    sa.Column('severity', postgresql.ENUM('mild', 'moderate', 'severe', 'anaphylaxis', name='allergy_severity'), nullable=False),
    sa.Column('noted_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_conditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('icd10', sa.Text(), nullable=False),
    sa.Column('name_uz', sa.Text(), nullable=False),
    sa.Column('name_ru', sa.Text(), nullable=True),
    sa.Column('kind', postgresql.ENUM('primary', 'comorbidity', 'past', name='condition_kind'), nullable=False),
    sa.Column('severity_note', sa.Text(), nullable=True),
    sa.Column('diagnosed_at', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_measurements',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('sbp_mmhg', sa.SmallInteger(), nullable=True),
    sa.Column('dbp_mmhg', sa.SmallInteger(), nullable=True),
    sa.Column('glucose_mmol', sa.Float(), nullable=True),
    sa.Column('source', postgresql.ENUM('patient', 'relative', 'doctor', 'nurse', 'admin', 'dispatcher', 'system', name='actor_kind'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_medications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('atc_code', sa.Text(), nullable=True),
    sa.Column('dose', sa.Text(), nullable=False),
    sa.Column('frequency', sa.Text(), nullable=False),
    sa.Column('route', sa.Text(), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('stopped_at', sa.Date(), nullable=True),
    sa.Column('stop_reason', sa.Text(), nullable=True),
    sa.Column('prescribed_by', sa.UUID(), nullable=True),
    sa.Column('affects_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescribed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_risk_factors',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('smoking', sa.Text(), nullable=True),
    sa.Column('smoking_pack_years', sa.Float(), nullable=True),
    sa.Column('alcohol', sa.Text(), nullable=True),
    sa.Column('diabetes', sa.Boolean(), nullable=False),
    sa.Column('hypertension', sa.Boolean(), nullable=False),
    sa.Column('ckd', sa.Boolean(), nullable=False),
    sa.Column('physical_activity', sa.Text(), nullable=True),
    sa.Column('lives_alone', sa.Boolean(), nullable=False),
    sa.Column('mobility', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_table('profile_audit',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('actor_kind', postgresql.ENUM('patient', 'relative', 'doctor', 'nurse', 'admin', 'dispatcher', 'system', name='actor_kind'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('entity', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('readings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hr_mean', sa.Float(), nullable=True),
    sa.Column('hr_min', sa.Float(), nullable=True),
    sa.Column('hr_max', sa.Float(), nullable=True),
    sa.Column('rmssd', sa.Float(), nullable=True),
    sa.Column('sdnn', sa.Float(), nullable=True),
    sa.Column('spo2', sa.Float(), nullable=True),
    sa.Column('skin_temp', sa.Float(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('rr_est', sa.Float(), nullable=True),
    sa.Column('sleep_frag', sa.Float(), nullable=True),
    sa.Column('worn', sa.Boolean(), nullable=False),
    sa.Column('battery', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'ts', name='uq_reading')
    )
    op.create_table('relatives',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('relationship', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('pin_hash', sa.Text(), nullable=True),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('is_emergency_contact', sa.Boolean(), nullable=False),
    sa.Column('contact_priority', sa.SmallInteger(), nullable=False),
    sa.Column('can_edit_profile', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token'),
    sa.UniqueConstraint('phone', 'patient_id', name='uq_relative_patient')
    )
    op.create_table('sos_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('source', postgresql.ENUM('watch_button', 'phone_app', 'relative_portal', 'auto_critical', name='sos_source'), nullable=False),
    sa.Column('status', postgresql.ENUM('raised', 'acknowledged', 'dispatched', 'resolved', 'false_alarm', 'cancelled', name='sos_status'), nullable=False),
    sa.Column('raised_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('address_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('clinical_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vitals_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('device_lat', sa.Float(), nullable=True),
    sa.Column('device_lon', sa.Float(), nullable=True),
    sa.Column('device_accuracy_m', sa.Float(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispatch_method', sa.Text(), nullable=True),
    sa.Column('dispatch_ref', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('twin_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_model', sa.Text(), nullable=True),
    sa.Column('prompt_hash', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_admissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('hospital_name', sa.Text(), nullable=False),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('admitted_at', sa.Date(), nullable=False),
    sa.Column('discharged_at', sa.Date(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('reason_icd10', sa.Text(), nullable=True),
    sa.Column('outcome', postgresql.ENUM('discharged', 'transferred', 'deceased', 'ongoing', name='admission_outcome'), nullable=False),
    sa.Column('was_readmission', sa.Boolean(), nullable=False),
    sa.Column('predicted_by_alert_id', sa.BigInteger(), nullable=True),
    sa.Column('discharge_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['predicted_by_alert_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('relative_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.CheckConstraint('num_nonnulls(user_id, relative_id, patient_id) = 1', name='chk_owner'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relative_id'], ['relatives.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('sos_notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sos_id', sa.UUID(), nullable=False),
    sa.Column('recipient_kind', postgresql.ENUM('patient', 'relative', 'doctor', 'nurse', 'admin', 'dispatcher', 'system', name='actor_kind'), nullable=False),
    sa.Column('recipient_ref', sa.Text(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sos_id'], ['sos_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('type', postgresql.ENUM('active_call', 'red_alert', name='task_type'), nullable=False),
    sa.Column('status', postgresql.ENUM('created', 'sent', 'seen', 'done', 'overdue', name='task_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reminded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('alert_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(
        'fk_patients_primary_address',
        'patients',
        'patient_addresses',
        ['primary_address_id'],
        ['id'],
        ondelete='SET NULL',
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # Break the patients <-> patient_addresses cycle before dropping either.
    op.drop_constraint('fk_patients_primary_address', 'patients', type_='foreignkey')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('sos_notifications')
    op.drop_table('refresh_tokens')
    op.drop_table('patient_admissions')
    op.drop_table('twin_snapshots')
    op.drop_table('sos_events')
    op.drop_table('relatives')
    op.drop_table('readings')
    op.drop_table('profile_audit')
    op.drop_table('patient_risk_factors')
    op.drop_table('patient_medications')
    op.drop_table('patient_measurements')
    op.drop_table('patient_conditions')
    op.drop_table('patient_allergies')
    op.drop_table('patient_addresses')
    op.drop_table('notifications')
    op.drop_table('baselines')
    op.drop_table('alerts')
    op.drop_table('patients')
    op.drop_table('users')

    # Enum types outlive their tables — drop them so upgrade is repeatable.
    op.execute('DROP TYPE IF EXISTS actor_kind')
    op.execute('DROP TYPE IF EXISTS address_kind')
    op.execute('DROP TYPE IF EXISTS admission_outcome')
    op.execute('DROP TYPE IF EXISTS alert_level')
    op.execute('DROP TYPE IF EXISTS allergy_severity')
    op.execute('DROP TYPE IF EXISTS baseline_param')
    op.execute('DROP TYPE IF EXISTS blood_group')
    op.execute('DROP TYPE IF EXISTS condition_kind')
    op.execute('DROP TYPE IF EXISTS patient_phase')
    op.execute('DROP TYPE IF EXISTS rh_factor')
    op.execute('DROP TYPE IF EXISTS sos_source')
    op.execute('DROP TYPE IF EXISTS sos_status')
    op.execute('DROP TYPE IF EXISTS task_status')
    op.execute('DROP TYPE IF EXISTS task_type')
    op.execute('DROP TYPE IF EXISTS user_role')

    # ### end Alembic commands ###
